
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './Navbar'
import HeadSection from './HeadSection'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Syvar Tech',
  description: 'Generated by create next app',
  icons: './assets/images/logo.jpg'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
     {/* <HeadSection/> */}
      <body className={inter.className}>
        <Navbar/>
        {children}</body>
    </html>
  )
}
